#quarkus:
#  devservices:
#    enable: false
#
#  datasource:
#    db-kind: postgresql
#    username: postgres
#    password: 7496
#    reactive:
#      url: postgresql://localhost:5433/test
#    jdbc:
#      url: jdbc:postgresql://localhost:5433/test
#      driver: org.postgresql.Driver
